name: booking
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  http: ^1.5.0   # âœ… Works with modern Flutter
  cupertino_icons: ^1.0.8
  page_transition: ^2.2.1
  carousel_slider: ^5.0.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/imgw.jpg
    - assets/images/imgwt.jpg
    - assets/images/login_bg.jpeg
    - assets/images/signup_bg.jpeg
    - assets/images/img1.jpg
    - assets/images/img2.jpg
    - assets/images/img3.jpg
    - assets/images/img4.jpg
    - assets/images/img5.jpg
    - assets/images/img6.jpg
    - assets/images/img7.jpg
    - assets/images/img8.jpg
    - assets/images/img9.jpg
    - assets/images/img10.jpg
    - assets/images/logo.png
    - assets/images/joya.jpg
    - assets/images/laico.jpg
    - assets/images/charme.jpg
    - assets/images/tulip.jpg
    - assets/images/amberelfell.jpg
    - assets/images/yadis.jpg
    - assets/images/darismail.jpg
    - assets/images/reviera.jpg
    - assets/images/Tamerza.jpg
    - assets/images/palacemahdia.jpg
    - assets/images/img11 (1).jpg
    - assets/images/img11 (2).jpg
    - assets/images/img11 (3).jpg
    - assets/images/img11 (4).jpg
    - assets/images/img11 (5).jpg
    - assets/images/img11 (6).jpg
    - assets/images/marhaba.jpg
    - assets/images/kanta.jpg
    - assets/images/pearl.jpg
    - assets/images/mahdiabeach.jpeg
    - assets/images/thapsus.jpg
    - assets/images/iberostar.jpg
    - assets/images/radisson.jpg
    - assets/images/plaza.jpg
    - assets/images/cigale.jpg
    - assets/images/mimosas.jpg
    - assets/images/itropika.jpg
    - assets/images/dareljeld.jpg
    - assets/images/thalassa.jpg
    - assets/images/hilton.jpg
    - assets/images/marina.jpg
    - assets/images/africajad.jpg
    - assets/images/djerbahood.jpeg
    - assets/images/ghriba.jpeg
    - assets/images/portelkantaoui.jpeg
    - assets/images/soukelattarine.jpeg
    - assets/images/madinahammamet.jpeg
    - assets/images/piratehammamet.jpeg
    - assets/images/sidibousaid.jpeg
    - assets/images/chatjrayid.jpeg
    - assets/images/palmier.jpeg
    - assets/images/plagenabeul.jpeg
    - assets/images/souknabeul.jpeg
    - assets/images/ribat.jpeg
    - assets/images/sidibousaid.jpeg
    - assets/images/soukelattarine.jpeg
    - assets/images/marina.jpeg
    - assets/images/jazz.jpeg
    - assets/images/foret.jpeg




